 
//--------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//--------------------------------------------------------------------------------------------------------------

namespace IDI.Core.Localization.Packages
{
    public partial class Resources
    {
        public partial class Prefix
        {
		    			public const string DISPLAY_NAME = "display-name";
						public const string VERIFICATION = "verification";
			        }

		public partial class Key
        {
		    			public const string CHARACTERS_MAXIMUM = "characters-maximum";
						public const string CHARACTERS_MINIMUM = "characters-minimum";
						public const string CHARACTERS_RANGE = "characters-range";
						public const string REQUIRED = "required";
						public const string TOKEN = "token";
			        }
    }
}