 
//--------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//--------------------------------------------------------------------------------------------------------------

namespace IDI.Core.Localization.Packages
{
    public class Resources
    {
        public class Prefix
        {
		    			public const string COMMAND = "command";
						public const string DISPLAY_NAME = "display-name";
						public const string VERIFICATION = "verification";
			        }

		public class Key 
		{
						public class Verification {
								public const string Required = "required";
								public const string CharactersRange = "characters-range";
								public const string CharactersMaximum = "characters-maximum";
								public const string CharactersMinimum = "characters-minimum";
								public const string DecimalRange = "decimal-range";
								public const string DecimalMaximum = "decimal-maximum";
								public const string DecimalMinimum = "decimal-minimum";
								}

						public class DisplayName {
								public const string Token = "token";
								}

						public class Command {
								public const string CommandNonsupport = "command-nonsupport";
								public const string UnknownCommand = "unknown-command";
								public const string CommandWithInvalidParameter = "command-with-invalid-parameter";
								public const string CommandInvalid = "command-invalid";
								public const string CommandExecutedWithError = "command-executed-with-error";
								}

					}
    }
}