 
//--------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//--------------------------------------------------------------------------------------------------------------

namespace IDI.Central.Domain.Localization
{
    public class Resources
    {
        public class Prefix
        {
		    			public const string COMMAND = "command";
						public const string DISPLAY_NAME = "display-name";
						public const string TAG = "tag";
			        }

		public class Key 
		{
						public class DisplayName {
								public const string ClientId = "client-id";
								public const string SecretKey = "secret-key";
								public const string Role = "role";
								public const string Username = "username";
								public const string Password = "password";
								public const string User = "user";
								public const string ConfirmPassword = "confirm-password";
								public const string ProductName = "product-name";
								public const string ProductCode = "product-code";
								public const string ProductTags = "product-tags";
								}

						public class Command {
								public const string InvalidUsernameOrPassword = "invalid-username-or-password";
								public const string AuthenticationSuccess = "authentication-success";
								public const string InvalidClient = "invalid-client";
								public const string InvalidUser = "invalid-user";
								public const string ClientDisabled = "client-disabled";
								public const string ClientAuthenticationFail = "client-authentication-fail";
								public const string ClientAuthenticationSuccess = "client-authentication-success";
								public const string SystemDataInitialized = "system-data-initialized";
								public const string SystemDataInitializeSuccess = "system-data-initialize-success";
								public const string InvalidRole = "invalid-role";
								public const string RoleAuthorizationSuccess = "role-authorization-success";
								public const string UserAuthorizationSuccess = "user-authorization-success";
								public const string RoleExists = "role-exists";
								public const string UsernameRegistered = "username-registered";
								public const string CreateSuccess = "create-success";
								public const string CreateFail = "create-fail";
								public const string UpdateSuccess = "update-success";
								public const string UpdateFail = "update-fail";
								public const string DeleteSuccess = "delete-success";
								public const string DeleteFail = "delete-fail";
								public const string RegisterSuccess = "register-success";
								public const string PasswordMismatch = "password-mismatch";
								public const string ProductCodeDuplicated = "product-code-duplicated";
								public const string ProductNotExisting = "product-not-existing";
								public const string RecordNotExisting = "record-not-existing";
								public const string TimeConflict = "time-conflict";
								}

						public class Tag {
								public const string Model = "model";
								public const string Spec = "spec";
								public const string Capacity = "capacity";
								public const string Weight = "weight";
								public const string Length = "length";
								public const string Height = "height";
								public const string Width = "width";
								public const string Size = "size";
								public const string Color = "color";
								public const string Year = "year";
								public const string Desc = "desc";
								}

					}
    }
}