 
//--------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//--------------------------------------------------------------------------------------------------------------

namespace IDI.Central.Domain.Localization
{
    public class Resources
    {
        public class Prefix
        {
		    			public const string COMMAND = "command";
						public const string DISPLAY_NAME = "display-name";
			        }

		public class Key
        {
		    			public const string AUTHENTICATION_SUCCESS = "authentication-success";
						public const string CLIENT_AUTHENTICATION_FAIL = "client-authentication-fail";
						public const string CLIENT_AUTHENTICATION_SUCCESS = "client-authentication-success";
						public const string CLIENT_DISABLED = "client-disabled";
						public const string CLIENT_ID = "client-id";
						public const string CONFIRM_PASSWORD = "confirm-password";
						public const string INVALID_CLIENT = "invalid-client";
						public const string INVALID_USERNAME_OR_PASSWORD = "invalid-username-or-password";
						public const string PASSWORD = "password";
						public const string ROLE = "role";
						public const string SECRET_KEY = "secret-key";
						public const string SYSTEM_DATA_INITIALIZED = "system-data-initialized";
						public const string SYSTEM_DATA_INITIALIZE_SUCCESS = "system-data-initialize-success";
						public const string USER = "user";
						public const string USERNAME = "username";
			        }
    }
}