 
//--------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//--------------------------------------------------------------------------------------------------------------

namespace IDI.Central.Domain.Localization
{
    public class Resources
    {
        public class Prefix
        {
		    			public const string COMMAND = "command";
						public const string TAG = "tag";
			        }

		public class Key 
		{
						public class Command {
								public const string AuthSuccess = "auth-success";
								public const string AuthFail = "auth-fail";
								public const string RetrieveUserInfoFail = "retrieve-user-info-fail";
								public const string InvalidUsernameOrPassword = "invalid-username-or-password";
								public const string InvalidClient = "invalid-client";
								public const string InvalidUser = "invalid-user";
								public const string InvalidRole = "invalid-role";
								public const string InvalidCategory = "invalid-category";
								public const string InvalidOrder = "invalid-order";
								public const string InvalidProduct = "invalid-product";
								public const string InvalidProductPrice = "invalid-product-price";
								public const string InvalidCustomer = "invalid-customer";
								public const string InvalidPayment = "invalid-payment";
								public const string IncompletedOrder = "incompleted-order";
								public const string ClientDisabled = "client-disabled";
								public const string ClientAuthenticationFail = "client-authentication-fail";
								public const string ClientAuthenticationSuccess = "client-authentication-success";
								public const string SysDbInitialized = "sys-db-initialized";
								public const string SysDbInitSuccess = "sys-db-init-success";
								public const string SysDataInitialized = "sys-data-initialized";
								public const string SysDataInitSuccess = "sys-data-init-success";
								public const string RoleAuthorizationSuccess = "role-authorization-success";
								public const string RoleExists = "role-exists";
								public const string UserAuthorizationSuccess = "user-authorization-success";
								public const string UserRegisterSuccess = "user-register-success";
								public const string UsernameRegistered = "username-registered";
								public const string CreateSuccess = "create-success";
								public const string CreateFail = "create-fail";
								public const string UpdateSuccess = "update-success";
								public const string UpdateFail = "update-fail";
								public const string DeleteSuccess = "delete-success";
								public const string DeleteFail = "delete-fail";
								public const string UploadSuccess = "upload-success";
								public const string UploadFail = "upload-fail";
								public const string SaveSuccess = "save-success";
								public const string SaveFail = "save-fail";
								public const string InboundSuccess = "inbound-success";
								public const string InboundFail = "inbound-fail";
								public const string OutboundSuccess = "outbound-success";
								public const string OutboundFail = "outbound-fail";
								public const string LowStocks = "low-stocks";
								public const string ProductOutOfStock = "product-out-of-stock";
								public const string OperationNonsupport = "operation-nonsupport";
								public const string OperationFail = "operation-fail";
								public const string OperationSuccess = "operation-success";
								public const string OperationLimited = "operation-limited";
								public const string PasswordMismatch = "password-mismatch";
								public const string ProductCodeDuplicated = "product-code-duplicated";
								public const string ProductNotExisting = "product-not-existing";
								public const string StoreNotExisting = "store-not-existing";
								public const string RecordNotExisting = "record-not-existing";
								public const string RecordDuplicated = "record-duplicated";
								public const string TimeConflict = "time-conflict";
								public const string OrderExists = "order-exists";
								public const string OrderUpdated = "order-updated";
								public const string OrderConfirmed = "order-confirmed";
								public const string TradeConfirmed = "trade-confirmed";
								public const string PhoneNumRegistered = "phone-num-registered";
								public const string RequiredSellingPrice = "required-selling-price";
								public const string NoFileUpload = "no-file-upload";
								public const string SupportedExtension = "supported-extension";
								public const string FileMaxSizeLimit = "file-max-size-limit";
								public const string PlsConfirmOrder = "pls-confirm-order";
								public const string Success = "success";
								public const string Completed = "completed";
								public const string Confirmed = "confirmed";
								public const string Unauthorized = "unauthorized";
								public const string TokenExpired = "token-expired";
								public const string TokenInvalid = "token-invalid";
								}

						public class Tag {
								public const string Model = "model";
								public const string Spec = "spec";
								public const string Capacity = "capacity";
								public const string Weight = "weight";
								public const string Length = "length";
								public const string Height = "height";
								public const string Width = "width";
								public const string Size = "size";
								public const string Color = "color";
								public const string Year = "year";
								public const string Desc = "desc";
								public const string Manufacturer = "manufacturer";
								public const string Processor = "processor";
								public const string Memory = "memory";
								public const string Display = "display";
								public const string Storage = "storage";
								}

					}
    }
}